runtime: nodejs20
instance_class: F1

handlers:
  # Handle static assets
  - url: /assets
    static_dir: dist/assets
    
  # Handle root
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    
  # Handle all other routes (for React Router)
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10